import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Onborda, OnbordaProvider, Step } from "onborda";
import CustomCard from "./_components/Card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const steps: Step[] = [
  {
    icon: "👋",
    title: "Welcome to this test app",
    content: (
      <div>
        <p>
          This is a test
        </p>
      </div>
    ),
    side: "top",
    showControls: true,
    selector: "#dashboard",
    pointerPadding: 10,
    pointerRadius: 10,
    nextRoute: "/",
    prevRoute: "/",
  },
  {
    icon: "👋",
    title: "Some other options",
    content: (
      <div>
        <p>
          This is another test
        </p>
      </div>
    ),
    side: "top",
    showControls: true,
    selector: "#actions",
    pointerPadding: 10,
    pointerRadius: 10,
    nextRoute: "/",
    prevRoute: "/",
  }
]


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <OnbordaProvider>
          <Onborda showOnborda steps={steps} cardComponent={CustomCard}>
            {children}
          </Onborda>
        </OnbordaProvider>
      </body>
    </html>
  );
}
